SELECT CASE
    WHEN GRADES.GRADE > 7 THEN Students.NAME
    ELSE NULL 
    END AS NAME,
    GRADES.GRADE,
    Students.MARKS
    FROM STUDENTS 
    JOIN GRADES 
    ON Students.MARKS BETWEEN MIN_MARK AND MAX_MARK
    ORDER BY GRADES.GRADE DESC,
    NAME ASC,
    Students.MARKS ASC;
